
const translations = {
  de: {
    web_title: "Julia & Peter — Hochzeitseinladung",
    countdown: "Countdown bis zur Hochzeit",
    update: "Update in",
    countdown_labels: {
      day: "Tag",
      days: "Tage",
      hour: "Std",
      hours: "Std",
      minute: "Min",
      minutes: "Min",
      second: "Sek",
      seconds: "Sek",
      today: "Heute ist der große Tag!"
    },
    title: "Julia & Peter",
    title2: "heiraten!",
    date: "03. Oktober 2026",
    letter_title: "Liebe Familie, liebe Freunde,",
    letter1: "was als fränkisch südtiroler Abenteuer in Marrakesch begann, wird nun besiegelt - wir heiraten.",
    letter2: "Und das möchten wir mit dir feiern!",
    letter3: "Nach der Trauung im Standesamt Brixen (Uhrzeit wird noch bekannt gegeben) verbringen wir den Tag am Burgerhof Meßner.",
    letter4: "Dort erwarten uns eine Mittagsjause, ein unklassischer Törggelen-Abend, gute Musik und jede Menge Spaß (Mehr zum Ablauf des Tages im Zuge des Updates).",
    letter5: "Wir haben Zimmer im Hotel Tourist reserviert, die gebucht werden können. Mehr Infos dazu ",
    letter6: "hier",
    letter7: "Bitte melde über das ",
    letter8: "Anmeldeformular",
    letter9: "unten bis zum ",
    letter10: "1. Mai 2026",
    letter11: "zurück, ob du kommen kannst.",
    letter12: "Der Tag soll frei von irgendwelchen Konventionen oder Zwängen sein. Dresscode ist demnach elegant, but not too serious (übersetzt: Anzug ja, Krawatte nein 😊).",
    letter13: "Wir freuen uns auf einen unvergesslichen Tag!",
    letter14: "Kontaktier",
    letter15: "uns gerne bei Fragen.",
    letter16: "P.S. Wenn du etwas schenken möchtest, freuen uns gerne über einen kleine finanzielle Unterstützung (die Verlobungsreise ist etwas ausgeartet 😄)",
    location_title: "Ort der Feier",
    location1: "Die Feier wird auf einem kleinen authentischen Bio Bauernhof stattfinden.",
    location2: "Dort erwarten uns stilecht südtiroler Spezialitäten, hausgemachte Weine und eine idyllische Atmosphäre.",
    address: "Adresse: Thalhoferstraße 7, 39042 Brixen, Italien",
    stay_title: "Übernachtung",
    stay_text1: "Wir haben Zimmer im Hotel Tourist reserviert:",
    room1: "Superior Doppelzimmer für 220€/Nacht (Mindestaufenthalt 2 Nächte) oder",
    room2: "Standardzimmer für 160€/Nacht (auch als Einzelzimmer möglich)",
    stay_text2: "Diese können bis zum 20. Juli telefonisch mit dem Code 'Hochzeit Julia & Peter' gebucht werden (📞 +39 0472 831545). Bezahlung dann vor Ort im Hotel.",
    stay_text3: "Natürlich sind auch andere Hotels, Pensionen oder Ferienwohnungen in der Umgebung möglich. Wir empfehlen aber in jedem Fall eine frühzeitige Buchung, weil Oktober Hauptsaison im Eisacktal ist und an diesem Tag auch noch ein Fest in Brixen stattfindet.",
    rsvp_title1: "Rückmeldung",
    rsvp_title2: "bitte 1x pro Person ausfüllen",
    name: "Name *",
    coming: "Kommst du? *",
    yes: "Ja",
    no: "Nein",
    eating: "Essen *",
    meat: "Fleisch",
    vegetarian: "Vegetarisch",
    allergies: "Unverträglichkeiten",
    travel: "Evtl. weißt du auch schon deine Reisepläne",
    travel_there: "Anreise ",
    travel_back: "Abreise ",
    submit: "Absenden",
    contact: "Kontakt",
    placeholders: {allergies: "z. B. Laktose, Gluten, Nüsse",},
    form: {
      submit: "Absenden",
      sending: "Senden...",
      success: "Vielen Dank! Eure Antwort wurde verschickt.",
      error: "Fehler beim Senden. Bitte erneut versuchen.",
      network: "Netzwerkfehler. Bitte später erneut versuchen."
    }
  },
  en: {
    web_title: "Julia & Peter — Wedding Invitation",
    countdown: "Countdown to the Wedding",
    update: "Update in",
    countdown_labels: {
      day: "day",
      days: "days",
      hour: "hr",
      hours: "hrs",
      minute: "min",
      minutes: "min",
      second: "sec",
      seconds: "sec",
      today: "Today is the big day!"
    },
    title: "Julia & Peter",
    title2: "are getting married!",
    date: "October 3, 2026",
    letter_title: "Dear family, dear friends,",
    letter1: "What began as a Franconian–South Tyrolean adventure in Marrakesh is now being sealed — we are getting married.",
    letter2: "And we would love to celebrate this with you!",
    letter3: "After the civil ceremony at the registry office in Brixen (time to be announced), we will spend the day at the Burgerhof Meßner.",
    letter4: "There, a light lunch, a non-traditional Törggelen evening, good music, and lots of fun await us (more details about the schedule will follow in the updates).",
    letter5: "We have reserved rooms at Hotel Tourist that can be booked. More information ",
    letter6: "here",
    letter7: "Please let us know via the ",
    letter8: "registration form",
    letter9: "below by ",
    letter10: "May 1, 2026",
    letter11: "whether you will be able to attend.",
    letter12: "The day should be free of any conventions or obligations. The dress code is therefore elegant, but not too serious (translated: suit yes, tie no 😊).",
    letter13: "We are looking forward to an unforgettable day!",
    letter14: "Feel free to contact",
    letter15: "us if you have any questions.",
    letter16: "P.S. If you would like to give a gift, we would be happy to receive a small financial contribution (the engagement trip got a bit out of hand 😄).",
    location_title: "Celebration Location",
    location1: "The celebration will take place on a small, authentic organic farm.",
    location2: "Traditional South Tyrolean specialties, homemade wines, and an idyllic atmosphere await us there.",
    address: "Address: Thalhoferstraße 7, 39042 Brixen, Italy",
    stay_title: "Accommodation",
    stay_text1: "We have reserved rooms at Hotel Tourist:",
    room1: "Superior double room for €220/night (minimum stay of 2 nights) or",
    room2: "Standard room for €160/night (also available as a single room)",
    stay_text2: "These can be booked by phone until July 20 using the code 'Wedding Julia & Peter' (📞 +39 0472 831545). Payment will be made directly at the hotel.",
    stay_text3: "Of course, other hotels, guesthouses, or vacation rentals in the area are also possible. However, we strongly recommend booking early, as October is peak season in the Eisack Valley and there will also be a festival in Brixen on that day.",
    rsvp_title1: "RSVP",
    rsvp_title2: "please fill out once per person",
    name: "Name *",
    coming: "Will you attend? *",
    yes: "Yes",
    no: "No",
    eating: "Meal *",
    meat: "Meat",
    vegetarian: "Vegetarian",
    allergies: "Food intolerances",
    travel: "You may already know your travel plans",
    travel_there: "Arrival",
    travel_back: "Departure",
    submit: "Submit",
    contact: "Contact",
    placeholders: {allergies: "e.g. lactose, gluten, nuts",},
    form: {
      submit: "Submit",
      sending: "Sending...",
      success: "Thank you! Your response has been sent.",
      error: "Error sending the form. Please try again.",
      network: "Network error. Please try again later."
    }
  },
  pl: {
    web_title: "Julia & Peter — Zaproszenie na Ślub",
    countdown: "Odliczanie do ślubu",
    update: "Aktualizacja za",
    countdown_labels: {
      day: "dzień",
      days: "dni",
      hour: "godz.",
      hours: "godz.",
      minute: "min",
      minutes: "min",
      second: "sek",
      seconds: "sek",
      today: "Dziś jest ten wielki dzień!"
    },
    title: "Julia & Peter",
    title2: "biorą ślub!",
    date: "3 października 2026",
    letter_title: "Drodzy Rodzino i Przyjaciele,",
    letter1: "To, co zaczęło się jako frankońsko–południowotyrolska przygoda w Marrakeszu, teraz staje się oficjalne — bierzemy ślub.",
    letter2: "I chcielibyśmy to świętować razem z Tobą!",
    letter3: "Po ceremonii w Urzędzie Stanu Cywilnego w Brixen (godzina zostanie podana później) spędzimy dzień w Burgerhof Meßner.",
    letter4: "Czeka nas lekki lunch, nietypowy wieczór Törggelen, dobra muzyka i mnóstwo zabawy (więcej szczegółów w kolejnych aktualizacjach).",
    letter5: "Zarezerwowaliśmy pokoje w Hotelu Tourist, które można rezerwować. Więcej informacji ",
    letter6: "tutaj",
    letter7: "Prosimy o potwierdzenie udziału poprzez ",
    letter8: "formularz zgłoszeniowy",
    letter9: "poniżej do ",
    letter10: "1 maja 2026",
    letter11: "czy będziesz mógł/mogła przyjść.",
    letter12: "Chcemy, aby ten dzień był wolny od konwencji i zobowiązań. Dress code jest więc elegancki, ale nie zbyt poważny (tzn.: garnitur tak, krawat nie 😊).",
    letter13: "Cieszymy się na niezapomniany dzień!",
    letter14: "Skontaktuj się",
    letter15: "z nami, jeśli masz pytania.",
    letter16: "P.S. Jeśli chciałbyś/chciałabyś podarować prezent, chętnie przyjmiemy drobny wkład finansowy (nasza podróż zaręczynowa trochę się rozrosła 😄).",
    location_title: "Miejsce uroczystości",
    location1: "Uroczystość odbędzie się na małym, autentycznym ekologicznym gospodarstwie.",
    location2: "Czekają na nas tradycyjne południowotyrolskie specjały, domowe wina i idylliczna atmosfera.",
    address: "Adres: Thalhoferstraße 7, 39042 Brixen, Włochy",
    stay_title: "Noclegi",
    stay_text1: "Zarezerwowaliśmy pokoje w Hotelu Tourist:",
    room1: "Pokój dwuosobowy Superior za 220€/noc (minimalny pobyt 2 noce) lub",
    room2: "Pokój standardowy za 160€/noc (możliwość zakwaterowania jako pokój jednoosobowy)",
    stay_text2: "Rezerwacje można dokonać telefonicznie do 20 lipca, używając kodu 'Wesele Julia & Peter' (📞 +39 0472 831545). Płatność na miejscu w hotelu.",
    stay_text3: "Oczywiście możliwe są też inne hotele, pensjonaty lub apartamenty w okolicy. Zalecamy jednak wcześniejszą rezerwację, ponieważ październik to sezon turystyczny w Eisacktal, a tego dnia w Brixen odbędzie się również festiwal.",
    rsvp_title1: "Potwierdzenie obecności",
    rsvp_title2: "prosimy wypełnić raz na osobę",
    name: "Imię i nazwisko *",
    coming: "Czy będziesz obecny/a? *",
    yes: "Tak",
    no: "Nie",
    eating: "Posiłek *",
    meat: "Mięso",
    vegetarian: "Wegetariański",
    allergies: "Alergie pokarmowe",
    travel: "Możesz już znać swoje plany podróży",
    travel_there: "Przyjazd",
    travel_back: "Wyjazd",
    submit: "Wyślij",
    contact: "Kontakt",
    placeholders: {allergies: "np. laktoza, gluten, orzechy",},
    form: {
      submit: "Wyślij",
      sending: "Wysyłanie...",
      success: "Dziękujemy! Twoja odpowiedź została wysłana.",
      error: "Błąd podczas wysyłania. Spróbuj ponownie.",
      network: "Błąd sieci. Spróbuj ponownie później."
    }
  },
  it: {
    web_title: "Julia & Peter — Invito al Matrimonio",
    countdown: "Conto alla rovescia per il matrimonio",
    update: "Aggiornamento tra",
    countdown_labels: {
      day: "giorno",
      days: "giorni",
      hour: "ora",
      hours: "ore",
      minute: "min",
      minutes: "min",
      second: "sec",
      seconds: "sec",
      today: "Oggi è il grande giorno!"
    },
    title: "Julia & Peter",
    title2: "si sposano!",
    date: "3 ottobre 2026",
    letter_title: "Cari familiari e amici,",
    letter1: "Quella che è iniziata come un’avventura franco–altoatesina a Marrakech ora diventa ufficiale — ci sposiamo.",
    letter2: "E vorremmo festeggiare questo giorno speciale con voi!",
    letter3: "Dopo la cerimonia civile al Comune di Bressanone (orario da comunicare), trascorreremo la giornata al Burgerhof Meßner.",
    letter4: "Ci aspettano un pranzo leggero, una serata Törggelen non convenzionale, buona musica e tanto divertimento (maggiori dettagli sul programma della giornata seguiranno con gli aggiornamenti).",
    letter5: "Abbiamo riservato delle camere presso l'Hotel Tourist, che possono essere prenotate. Maggiori informazioni ",
    letter6: "qui",
    letter7: "Vi preghiamo di confermare la vostra partecipazione tramite il ",
    letter8: "modulo di registrazione",
    letter9: "qui sotto entro il ",
    letter10: "1 maggio 2026",
    letter11: "se potrete partecipare.",
    letter12: "Vogliamo che questa giornata sia libera da convenzioni o obblighi. Il dress code è quindi elegante, ma non troppo serio (tradotto: abito sì, cravatta no 😊).",
    letter13: "Non vediamo l’ora di condividere una giornata indimenticabile con voi!",
    letter14: "Non esitate a contattare",
    letter15: "ci per qualsiasi domanda.",
    letter16: "P.S. Se desiderate fare un regalo, saremo felici di ricevere un piccolo contributo economico (il viaggio di fidanzamento è un po’ sfuggito di mano 😄).",
    location_title: "Luogo della festa",
    location1: "La festa si terrà in una piccola e autentica fattoria biologica.",
    location2: "Ci aspettano specialità tradizionali altoatesine, vini fatti in casa e un’atmosfera idilliaca.",
    address: "Indirizzo: Thalhoferstraße 7, 39042 Bressanone, Italia",
    stay_title: "Sistemazione",
    stay_text1: "Abbiamo riservato camere presso l'Hotel Tourist:",
    room1: "Camera doppia Superior a 220€/notte (soggiorno minimo 2 notti) oppure",
    room2: "Camera standard a 160€/notte (disponibile anche come singola)",
    stay_text2: "Le camere possono essere prenotate telefonicamente entro il 20 luglio con il codice 'Matrimonio Julia & Peter' (📞 +39 0472 831545). Pagamento direttamente in hotel.",
    stay_text3: "Ovviamente sono disponibili anche altri hotel, pensioni o appartamenti nella zona. Consigliamo comunque di prenotare per tempo, poiché ottobre è alta stagione nella Valle Isarco e lo stesso giorno si terrà anche un festival a Bressanone.",
    rsvp_title1: "RSVP",
    rsvp_title2: "per favore compilare una volta per persona",
    name: "Nome *",
    coming: "Parteciperai? *",
    yes: "Sì",
    no: "No",
    eating: "Pasto *",
    meat: "Carne",
    vegetarian: "Vegetariano",
    allergies: "Intolleranze alimentari",
    travel: "Puoi già conoscere i tuoi piani di viaggio",
    travel_there: "Arrivo",
    travel_back: "Partenza",
    submit: "Invia",
    contact: "Contatto",
    placeholders: {allergies: "es. lattosio, glutine, frutta a guscio",},
    form: {
      submit: "Invia",
      sending: "Invio in corso...",
      success: "Grazie! La tua risposta è stata inviata.",
      error: "Errore durante l’invio. Per favore riprova.",
      network: "Errore di rete. Riprova più tardi."
    }
  },
  es: {
    web_title: "Julia & Peter — Invitación de Boda",
    countdown: "Cuenta regresiva para la boda",
    update: "Actualización en",
    countdown_labels: {
      day: "día",
      days: "días",
      hour: "h",
      hours: "h",
      minute: "min",
      minutes: "min",
      second: "s",
      seconds: "s",
      today: "¡Hoy es el gran día!"
    },
    title: "Julia & Peter",
    title2: "¡se casan!",
    date: "3 de octubre de 2026",
    letter_title: "Querida familia, queridos amigos,",
    letter1: "Lo que comenzó como una aventura franco–altoatesina en Marrakech ahora se vuelve oficial — nos casamos.",
    letter2: "¡Y nos encantaría celebrarlo contigo!",
    letter3: "Después de la ceremonia civil en el Registro Civil de Bressanone (hora por confirmar), pasaremos el día en el Burgerhof Meßner.",
    letter4: "Nos espera un almuerzo ligero, una velada Törggelen no tradicional, buena música y mucha diversión (más detalles sobre el programa del día se darán en próximas actualizaciones).",
    letter5: "Hemos reservado habitaciones en el Hotel Tourist, que se pueden reservar. Más información ",
    letter6: "aquí",
    letter7: "Por favor, confirma tu asistencia a través del ",
    letter8: "formulario de registro",
    letter9: "a continuación antes del ",
    letter10: "1 de mayo de 2026",
    letter11: "para decirnos si podrás asistir.",
    letter12: "Queremos que el día sea libre de convenciones y obligaciones. El código de vestimenta es elegante, pero no demasiado serio (es decir: traje sí, corbata no 😊).",
    letter13: "¡Estamos deseando compartir un día inolvidable contigo!",
    letter14: "No dudes en contactar",
    letter15: "con nosotros si tienes alguna pregunta.",
    letter16: "P.D. Si deseas hacer un regalo, nos encantaría recibir una pequeña contribución económica (¡el viaje de compromiso se nos fue un poco de las manos 😄!).",
    location_title: "Lugar de la celebración",
    location1: "La celebración tendrá lugar en una pequeña y auténtica granja ecológica.",
    location2: "Nos esperan especialidades tradicionales del Tirol del Sur, vinos caseros y un ambiente idílico.",
    address: "Dirección: Thalhoferstraße 7, 39042 Bressanone, Italia",
    stay_title: "Alojamiento",
    stay_text1: "Hemos reservado habitaciones en el Hotel Tourist:",
    room1: "Habitación doble Superior por 220€/noche (estancia mínima de 2 noches) o",
    room2: "Habitación estándar por 160€/noche (también disponible como individual)",
    stay_text2: "Las habitaciones se pueden reservar por teléfono hasta el 20 de julio con el código 'Boda Julia & Peter' (📞 +39 0472 831545). El pago se realiza directamente en el hotel.",
    stay_text3: "Por supuesto, también hay otros hoteles, pensiones o apartamentos en la zona. Sin embargo, recomendamos reservar con anticipación, ya que octubre es temporada alta en el Valle de Isarco y ese día también habrá un festival en Bressanone.",
    rsvp_title1: "Confirmación",
    rsvp_title2: "por favor, completar una vez por persona",
    name: "Nombre *",
    coming: "¿Asistirás? *",
    yes: "Sí",
    no: "No",
    eating: "Comida *",
    meat: "Carne",
    vegetarian: "Vegetariano",
    allergies: "Alergias alimentarias",
    travel: "Quizás ya conozcas tus planes de viaje",
    travel_there: "Llegada",
    travel_back: "Salida",
    submit: "Enviar",
    contact: "Contacto",
    placeholders: {allergies: "p. ej. lactosa, gluten, frutos secos",},
    form: {
      submit: "Enviar",
      sending: "Enviando...",
      success: "¡Gracias! Tu respuesta ha sido enviada.",
      error: "Error al enviar. Por favor, inténtalo de nuevo.",
      network: "Error de red. Por favor, inténtalo más tarde."
    }
  }
};

function translatePage(lang) {
  const dict = translations[lang];
  if (!dict) return;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (dict[key]) {
      el.textContent = dict[key];
    }
  });

  translatePlaceholders(lang);

  document.documentElement.lang = lang;
  localStorage.setItem('lang', lang);
}
